#!/usr/bin/env python

import pprint
import json
from tatsu import parse, compile
from tatsu.util import asjson

grammar    = "".join(open("lib/dokimi.ebnf", "r").readlines())
definition = "".join(open("def/01-assignments.dok").readlines())

print('# DEF')
pprint.pprint(definition)

ast = parse(grammar, definition)

print('# PPRINT')
pprint.pprint(ast, indent=2, width=20)
print()


