@@grammar::Dokimi

start
    =
    stmt { stmt } + $
    ;

stmt
    =
    | assignment
    | symbol
    ;

assignment
    =
    symbol call symbol
    ;

call
    =
    ( ' ' | '.' ) symbol
    ;

symbol
    =
    /\S+/
    ;

